# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2026 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: latheRecipe
  id: SprayPainterMagic
  completetime: 6
  result: SprayPainterMagic
  materials:
    Bluespace: 100
    Plastic: 1000
    Steel: 500
    Silver: 100
    Plasma: 200

- type: latheRecipe
  id: CrayonMagic
  completetime: 6
  result: CrayonMagic
  materials:
    Bluespace: 100
    Plastic: 500
    Plasma: 200
