# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2026 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: latheRecipePack
  id: LuaBluespaceArt
  recipes:
  - SprayPainterMagic
  - CrayonMagic
