# DH-Commented: Убираю этот акшон, у нас нет сортировщиков 
# меток на гите, да и толку от неё только засоряет (schrodinger71)
# name: "Labels: Untriaged"

# on:
#   issues:
#     types: [opened]
#   pull_request_target:
#     types: [opened]

# jobs:
#   add_label:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions-ecosystem/action-add-labels@v1
#       if: join(github.event.issue.labels) == ''
#       with:
#         labels: "S: Untriaged"
